/* macro substitution is used to define matching static arrays using this file */
defineBrand( kBrand3DLab, "3D Lab")
defineBrand( kBrandAMW, "AMW")
defineBrand( kBrandAOC, "AOC")
defineBrand( kBrandATT, "ATT")
defineBrand( kBrandAccurian, "Accurian")
defineBrand( kBrandAcousticResearch, "Acoustic Research")
defineBrand( kBrandAdcom, "Adcom")
defineBrand( kBrandAdmiral, "Admiral")
defineBrand( kBrandAiwa, "Aiwa")
defineBrand( kBrandAkai, "Akai")
defineBrand( kBrandAllegro, "Allegro")
defineBrand( kBrandApex, "Apex")
defineBrand( kBrandArrgo, "Arrgo")
defineBrand( kBrandAstar, "Astar")
defineBrand( kBrandAudioAccess, "Audio Access")
defineBrand( kBrandAudiovox, "Audiovox")
defineBrand( kBrandAurora, "Aurora")
defineBrand( kBrandBellAndHowell, "Bell & Howell")
defineBrand( kBrandBellExpressVu, "Bell ExpressVu")
defineBrand( kBrandBenQ, "BenQ")
defineBrand( kBrandBose, "Bose")
defineBrand( kBrandBrand, "Brand")
defineBrand( kBrandBroksonic, "Broksonic")
defineBrand( kBrandCaliforniaAudioLabs, "California Audio Labs")
defineBrand( kBrandCanalPlus, "CanalPlus")
defineBrand( kBrandCarver, "Carver")
defineBrand( kBrandCasio, "Casio")
defineBrand( kBrandCisco, "Cisco")
defineBrand( kBrandCitizen, "Citizen")
defineBrand( kBrandCoby, "Coby")
defineBrand( kBrandComcastMotorola, "Comcast/Motorola")
defineBrand( kBrandCurtis, "Curtis")
defineBrand( kBrandCurtisMathes, "Curtis Mathes")
defineBrand( kBrandCyberHome, "CyberHome")
defineBrand( kBrandDISH, "DISH")
defineBrand( kBrandDaewoo, "Daewoo")
defineBrand( kBrandDell, "Dell")
defineBrand( kBrandDenon, "Denon")
defineBrand( kBrandDigitalStream, "Digital Stream")
defineBrand( kBrandDish, "Dish")
defineBrand( kBrandDurabrand, "Durabrand")
defineBrand( kBrandDynex, "Dynex")
defineBrand( kBrandElectrohome, "Electrohome")
defineBrand( kBrandElementElectronics, "Element Electronics")
defineBrand( kBrandEmerson, "Emerson")
defineBrand( kBrandEpson, "Epson")
defineBrand( kBrandFaroudja, "Faroudja")
defineBrand( kBrandFisher, "Fisher")
defineBrand( kBrandFluid, "Fluid")
defineBrand( kBrandFosgate, "Fosgate")
defineBrand( kBrandFujitsu, "Fujitsu")
defineBrand( kBrandFunai, "Funai")
defineBrand( kBrandGateway, "Gateway")
defineBrand( kBrandGeneralElectric, "General Electric")
defineBrand( kBrandGoVideo, "GoVideo")
defineBrand( kBrandHaier, "Haier")
defineBrand( kBrandHannspree, "Hannspree")
defineBrand( kBrandHarmanKardon, "Harman Kardon")
defineBrand( kBrandHewlettPackard, "Hewlett Packard")
defineBrand( kBrandHitachi, "Hitachi")
defineBrand( kBrandHughes, "Hughes")
defineBrand( kBrandHyundai, "Hyundai")
defineBrand( kBrandiLive, "iLive")
defineBrand( kBrandILO, "ILO")
defineBrand( kBrandINOi, "INOi")
defineBrand( kBrandInsignia, "Insignia")
defineBrand( kBrandJBL, "JBL")
defineBrand( kBrandJVC, "JVC")
defineBrand( kBrandJensen, "Jensen")
defineBrand( kBrandJwin, "Jwin")
defineBrand( kBrandKenwood, "Kenwood")
defineBrand( kBrandKlipsch, "Klipsch")
defineBrand( kBrandKonka, "Konka")
defineBrand( kBrandKoss, "Koss")
defineBrand( kBrandKrell, "Krell")
defineBrand( kBrandLG, "LG")
defineBrand( kBrandLexicon, "Lexicon")
defineBrand( kBrandLoewe, "Loewe")
defineBrand( kBrandLuxman, "Luxman")
defineBrand( kBrandMagnavox, "Magnavox")
defineBrand( kBrandMarantz, "Marantz")
defineBrand( kBrandMcIntosh, "McIntosh")
defineBrand( kBrandMemorex, "Memorex")
defineBrand( kBrandMitsubishi, "Mitsubishi")
defineBrand( kBrandMoxi, "Moxi")
defineBrand( kBrandNAD, "NAD")
defineBrand( kBrandNEC, "NEC")
defineBrand( kBrandNFusion, "NFusion")
defineBrand( kBrandNakamichi, "Nakamichi")
defineBrand( kBrandNexus, "Nexus")
defineBrand( kBrandNikko, "Nikko")
defineBrand( kBrandOnkyo, "Onkyo")
defineBrand( kBrandOppo, "Oppo")
defineBrand( kBrandOptimus, "Optimus")
defineBrand( kBrandOptoma, "Optoma")
defineBrand( kBrandOrion, "Orion")
defineBrand( kBrandOritron, "Oritron")
defineBrand( kBrandPace, "Pace")
defineBrand( kBrandPanasonic, "Panasonic")
defineBrand( kBrandPansat, "Pansat")
defineBrand( kBrandParasound, "Parasound")
defineBrand( kBrandPhilips, "Philips")
defineBrand( kBrandPicoMacom, "Pico Macom")
defineBrand( kBrandPioneer, "Pioneer")
defineBrand( kBrandPolaroid, "Polaroid")
defineBrand( kBrandProScan, "ProScan")
defineBrand( kBrandProtron, "Protron")
defineBrand( kBrandPyle, "Pyle")
defineBrand( kBrandRCA, "RCA")
defineBrand( kBrandRSQ, "RSQ")
defineBrand( kBrandRadioShack, "RadioShack")
defineBrand( kBrandRotel, "Rotel")
defineBrand( kBrandSabrent, "Sabrent")
defineBrand( kBrandSamsung, "Samsung")
defineBrand( kBrandSansui, "Sansui")
defineBrand( kBrandSanyo, "Sanyo")
defineBrand( kBrandSceptre, "Sceptre")
defineBrand( kBrandScientificAtlanta, "Scientific Atlanta")
defineBrand( kBrandScott, "Scott")
defineBrand( kBrandSensoryScience, "Sensory Science")
defineBrand( kBrandSharp, "Sharp")
defineBrand( kBrandSherwood, "Sherwood")
defineBrand( kBrandSlingMedia, "Sling Media")
defineBrand( kBrandSonicview, "Sonicview")
defineBrand( kBrandSony, "Sony")
defineBrand( kBrandSoundesign, "Soundesign")
defineBrand( kBrandSunBrite, "SunBrite")
defineBrand( kBrandSylvania, "Sylvania")
defineBrand( kBrandSymphonic, "Symphonic")
defineBrand( kBrandSyntax, "Syntax")
defineBrand( kBrandTCL, "TCL")
defineBrand( kBrandTeac, "Teac")
defineBrand( kBrandTechnics, "Technics")
defineBrand( kBrandTivo, "Tivo")
defineBrand( kBrandToshiba, "Toshiba")
defineBrand( kBrandTristar, "Tristar")
defineBrand( kBrandTruTech, "TruTech")
defineBrand( kBrandViore, "Viore")
defineBrand( kBrandVisionQuest, "Vision Quest")
defineBrand( kBrandVivitek, "Vivitek")
defineBrand( kBrandVizio, "Vizio")
defineBrand( kBrandWestinghouse, "Westinghouse")
defineBrand( kBrandYamaha, "Yamaha")
defineBrand( kBrandZenith, "Zenith")
