/*
    @file generateHashes.c

    calculates hashes for a collection of fixed strings at build time.
    
    The hashes are output in the form of a preprocessor #define, so can
    be used inline as constants, e.g. in switch statements.
    This seriously speeds up comparisons of a string against a dictionary
    of fixed strings, in the same way using a hash table does, and makes
    the code easier to write & maintain.
    Note that this tool does not check for hash collisions. Presumably a
    collision would cause a compiler error if used in a switch statement.

    Copyright 2011, Paul Chambers. All Rights Reserved.
*/

#include "common.h"
#include "analyse-ir-codes.h"   /* contains the definition of STRING_HASH_STEP */

const char *gStringConstants[] = {
    "Full_Repeat",
    "Partial_Repeat",
    "Repeat",
    "Toggle",
    NULL
};

unsigned long stringToHash(const char *str)
{
    const char *s = str;
    unsigned long hash = 0;

    while (*s != '\0')
        hash = STRING_HASH_STEP(hash, *s++);

    return hash;
}

/*
    process the arbitrary string to something that can be used in a #defined symbol
*/
const char *stringToSymbol(const char *str)
{
    const char *s = str;
    char *d, *dest;
    int capitalize = 0;

    dest = calloc( strlen(s), sizeof(char) );
    d = dest;

    while (*s != '\0')
    {
        if (isspace(*s) || ispunct(*s))
            capitalize = 1;
        else {
            *d++ = capitalize ? toupper(*s) : *s;
            capitalize = 0;
        }
        ++s;
    }
    return (const char *)dest;
}

int main(int UNUSED(argc), char ** UNUSED(argv))
{
    const char *string, *symbol;
    unsigned long hash;
    int i;

    printf("/* automatically generated by generateHashes - DO NOT EDIT! */\n");

    for (i = 0; (string = gStringConstants[i]) != NULL; ++i)
    {
        symbol = stringToSymbol(string);
        hash = stringToHash(string);
        printf("#define qHash%-32s (0x%08lx)\n", symbol, hash);
        free((void *)symbol);
    }
    
    return 0;
}
