OBJS = analyse-ir-codes.o import.o analyse.o export.o logging.o

CFLAGS += -ggdb -O3 -pedantic -std=c99 -Wall -Wextra -Wno-missing-field-initializers -Wunused
#CFLAGS  += -fmudflap
#LDFLAGS += -lmudflap

.PHONY: all clean install timestamp

all: analyse-ir-codes

clean:
	rm -vf ${OBJS} generateHashes.o generateHashes fuzzytest.o 

analyse-ir-codes: ${OBJS}

analyse-ir-codes.o: import.h analyse.h timestamp.h

import.o: import.h stringHashes.h codesetmapping.h

analyse.o: analyse.h

export.o: export.h

logging.o: logging.h

${OBJS}: common.h analyse-ir-codes.h

common.h: timestamp.h logging.h

analyse-ir-codes.h: devicetypemapping.h brandmapping.h

stringHashes.h: generateHashes
	./generateHashes > stringHashes.h

generateHashes.c: common.h analyse-ir-codes.h

timestamp.h: timestamp
	echo "/* generated by build - do not edit */" > timestamp.h
	echo "#define BUILD_DATE       `date '+"%A, %B %d"'`" >> timestamp.h
	echo "#define EXPIRY_DATE      `date --date "2 weeks" '+"%A, %B %d"'`" >> timestamp.h
	echo "#define EXPIRY_TIMESTAMP `date --date "00:00 15 days" +%sUL`" >> timestamp.h

fuzzytest: fuzzytest.o

