/* automatically generated by generateHashes - DO NOT EDIT! */
#define qHashFullRepeat                       (0x0814c8db)
#define qHashPartialRepeat                    (0xa6d1a33b)
#define qHashRepeat                           (0xc651e3d7)
#define qHashToggle                           (0xc2607712)
